/**
 * Pre-bundles the client-side JS module into a self-contained string
 * with all dependencies inlined. This is necessary because Expressive Code's
 * `jsModules` API injects raw JS into the page without any import resolution.
 *
 * Bare module specifiers (e.g. 'shiki-magic-move/core') would fail in
 * production builds where there is no bundler to resolve them at runtime.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));

const result = await build({
	entryPoints: [join(__dirname, 'magic-move.js')],
	bundle: true,
	format: 'esm',
	minify: true,
	write: false,
	platform: 'browser',
	target: 'es2022',
	banner: {
		js: '/* shiki-magic-move/renderer | MIT License | Copyright (c) 2022 Anthony Fu <https://github.com/antfu> */',
	},
});

const code = result.outputFiles[0].text.trim();
const output = `// Auto-generated by src/js-module/build.mjs – do not edit manually\nexport const jsModule = ${JSON.stringify(code)};\n`;

writeFileSync(join(__dirname, 'magic-move.min.ts'), output);

console.log(
	`Built magic-move.min.ts (${(code.length / 1024).toFixed(1)} KB minified)`,
);
